import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    Enum,
    Index,
    Integer,
    String,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.modules.cases.domain.entities.enums import (
    CaseSeverity,
    CaseStatus,
    CaseType,
    ResolutionAction,
)
from app.platform.database.models import Base, UUIDPrimaryKeyMixin

if TYPE_CHECKING:
    from app.modules.cases.domain.entities.case_evidence_item import CaseEvidenceItem
    from app.modules.cases.domain.entities.case_timeline_event import CaseTimelineEvent

SCHEMA = "cases"

#: A resolution note is the compliance record of why a case was closed the way
#: it was. Mirrors customers.customer_review's MIN_OUTCOME_RATIONALE_LENGTH
#: pattern, but at length > 0 rather than a 50-character floor: S1T1's
#: acceptance criteria asks only that a null/empty note be rejected, not that it
#: meet a substantive-length bar.
MIN_RESOLUTION_NOTE_LENGTH = 1


class ComplianceCase(UUIDPrimaryKeyMixin, Base):
    """One compliance case — a screening hit, a reconciliation break, an
    onboarding review, or any of the other originating events Epic 4.3 covers.

    Not built on `AnerModel`: this entity's second timestamp is
    `last_updated_at`, not `updated_at`, so the column-name mismatch rules out
    `TimestampMixin`. The UUID primary key is still shared via
    `UUIDPrimaryKeyMixin`.

    `case_reference` is generated by a database trigger
    (`cases.generate_case_reference`, defined in the migration) rather than in
    application code, so that the per-calendar-year sequence it draws from
    (`cases.case_reference_sequence`) is atomic under concurrent inserts no
    matter which service or code path creates the row. The trigger only fills
    the column when it is left NULL, so a caller (or a test proving the unique
    constraint) may still supply an explicit value.
    """

    __tablename__ = "compliance_case"
    __table_args__ = (
        UniqueConstraint("case_reference", name="uq_compliance_case_reference"),
        CheckConstraint(
            "case_reference ~ '^CASE-[0-9]{4}-[0-9]+$'",
            name="ck_compliance_case_reference_format",
        ),
        CheckConstraint(
            "priority BETWEEN 1 AND 5",
            name="ck_compliance_case_priority_range",
        ),
        # The idempotency guard against duplicate Kafka events creating
        # duplicate cases. A plain UniqueConstraint would also forbid a second
        # NULL, which is the common case for cases raised without a single
        # originating event (e.g. MANUAL) — so this is a partial unique index
        # instead, following the precedent of
        # onboarding_request's uq_onboarding_request_active_customer.
        Index(
            "uq_compliance_case_originating_event_id",
            "originating_event_id",
            unique=True,
            postgresql_where=text("originating_event_id IS NOT NULL"),
        ),
        # A resolution is only a resolution if it says why. Mirrors
        # ck_customer_review_completion_recorded: bind the note requirement to
        # the field that triggers it, not to every row regardless of state.
        CheckConstraint(
            "resolution_action IS NULL OR ("
            " resolution_note IS NOT NULL"
            f" AND char_length(btrim(resolution_note)) >= {MIN_RESOLUTION_NOTE_LENGTH}"
            ")",
            name="ck_compliance_case_resolution_note_required",
        ),
        # ONBOARDING_INTAKE is a holding state — RXIL data has arrived but
        # required documents/checks aren't all in, so there is nothing yet to
        # derive an SLA from (see enums.py's CaseType.ONBOARDING_INTAKE and
        # sla_config_loader.EXPECTED_CASE_TYPES). Added in
        # cases_0003_intake_sla_null; every other case_type keeps
        # requiring a deadline at the application layer, but only this one is
        # forbidden from having one, so the constraint is one-directional.
        CheckConstraint(
            "case_type <> 'ONBOARDING_INTAKE' OR sla_deadline IS NULL",
            name="ck_compliance_case_intake_has_no_sla_deadline",
        ),
        Index("ix_compliance_case_status_sla", "case_status", "sla_deadline"),
        Index("ix_compliance_case_customer_id", "customer_id"),
        Index("ix_compliance_case_settlement_id", "settlement_id"),
        Index("ix_compliance_case_onboarding_id", "onboarding_id"),
        Index("ix_compliance_case_assigned_to", "assigned_to"),
        {"schema": SCHEMA},
    )

    # ── Identity ──────────────────────────────────────────────────────────────
    case_reference: Mapped[str] = mapped_column(String(64), nullable=False)
    case_type: Mapped[CaseType] = mapped_column(
        Enum(CaseType, name="case_type_enum", schema=SCHEMA), nullable=False
    )
    case_status: Mapped[CaseStatus] = mapped_column(
        Enum(CaseStatus, name="case_status_enum", schema=SCHEMA), nullable=False
    )
    severity: Mapped[CaseSeverity] = mapped_column(
        Enum(CaseSeverity, name="case_severity_enum", schema=SCHEMA), nullable=False
    )
    priority: Mapped[int] = mapped_column(Integer, nullable=False)
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str] = mapped_column(String, nullable=False)

    # ── Subject — the record under review, whichever epic it belongs to ───────
    # Deliberately no foreign keys: a case can name a customer, a settlement or
    # an onboarding request across schema boundaries, and Epic 4.3 does not
    # (yet) have a cross-module reference-integrity mechanism for that — the
    # same trade-off onboarding_case.provider_route_id already documents for a
    # not-yet-existent table. All three stay bare, nullable UUIDs.
    customer_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    settlement_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    onboarding_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)

    # ── Origin — what raised this case, and the idempotency guard ─────────────
    originating_epic: Mapped[str] = mapped_column(String(100), nullable=False)
    originating_event_type: Mapped[str] = mapped_column(String(150), nullable=False)
    originating_event_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True
    )

    # ── Assignment ──────────────────────────────────────────────────────────
    assigned_to: Mapped[str | None] = mapped_column(String(255), nullable=True)
    assigned_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # ── SLA ─────────────────────────────────────────────────────────────────
    # Set once — by the S1T2 SLA service at creation for every case_type except
    # ONBOARDING_INTAKE, or by application/case_transition_service.py's
    # `transition_case_to_review` the moment an ONBOARDING_INTAKE case becomes
    # ONBOARDING_REVIEW — and never moved by a config redeploy — see
    # application/sla_service.py and infrastructure/sla_config_loader.py's
    # module docstring. Nullable because an ONBOARDING_INTAKE case has no SLA
    # yet (ck_compliance_case_intake_has_no_sla_deadline enforces this at the
    # database level too); every other case_type is expected to have one set
    # at creation even though the column itself no longer requires it.
    sla_deadline: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    sla_breached: Mapped[bool] = mapped_column(Boolean, nullable=False)

    # ── Resolution ──────────────────────────────────────────────────────────
    resolution_action: Mapped[ResolutionAction | None] = mapped_column(
        Enum(ResolutionAction, name="resolution_action_enum", schema=SCHEMA), nullable=True
    )
    resolution_note: Mapped[str | None] = mapped_column(String, nullable=True)
    resolution_approval_request_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True
    )
    # Immutable once set (cases_0001's field-immutability trigger). A case
    # resolved twice, or resolved by someone other than who the record says,
    # is not a compliance record a regulator can rely on.
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    resolved_by: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # ── Evidence ────────────────────────────────────────────────────────────
    # The aggregated evidence package a reviewer sees. Individual evidence is
    # also recorded per-item in case_evidence_item; this column is the rolled-up
    # view a case's own row carries. Same encrypted-at-rest documentation gap as
    # case_evidence_item.evidence_data applies whenever this package embeds a
    # PII-bearing evidence type.
    evidence_package: Mapped[dict] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )

    # ── Timestamps ──────────────────────────────────────────────────────────
    # Immutable once set (cases_0001's field-immutability trigger, unconditional
    # for this column since it always holds a value from insert).
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    last_updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )

    # ── Read relationships (ANER-4.3-S6T1) ────────────────────────────────────
    # `viewonly=True`, one-directional, no `back_populates`: `case_evidence_item`
    # and `case_timeline_event` are written exclusively through
    # `EvidenceAggregationService` / `CaseLifecycleService` / `CaseNoteService`
    # (raw inserts keyed by `case_id`), never by assigning into a collection on
    # a loaded `ComplianceCase`. A writable relationship here (the default) would
    # let SQLAlchemy's unit-of-work believe it owns these children and attempt a
    # cascade on flush/delete — `case_timeline_event` rejects UPDATE/DELETE
    # outright at the database level (append-only trigger), so a writable
    # relationship would surface as a confusing trigger error the first time
    # some unrelated flush touched a loaded collection. `viewonly=True` makes
    # both relationships exist for exactly one purpose: letting
    # `CaseQueryService.get_case_detail` (S6T1) eager-load a case with its
    # evidence and timeline in O(1) queries via `selectinload`, instead of the
    # N+1 pattern a per-item query loop would produce.
    # `ComplianceCase` (unqualified) is ambiguous in this declarative base's
    # registry — `app.modules.compliance.domain.entities.compliance` defines
    # its own, unrelated `ComplianceCase` (see this module's class docstring
    # and the package README's "Boundary with compliance.compliance_cases"
    # section). SQLAlchemy's string-based relationship resolution raises
    # `InvalidRequestError: Multiple classes found for path "ComplianceCase"`
    # unless the primaryjoin spells out the fully module-qualified path — the
    # exact collision this module's own docs warned would bite "anyone
    # reading an unqualified ComplianceCase import", now bitten by a
    # relationship string instead of a Python import.
    evidence_items: Mapped[list["CaseEvidenceItem"]] = relationship(
        "CaseEvidenceItem",
        primaryjoin=(
            "app.modules.cases.domain.entities.compliance_case.ComplianceCase.id "
            "== CaseEvidenceItem.case_id"
        ),
        order_by="CaseEvidenceItem.added_at",
        viewonly=True,
    )
    timeline_events: Mapped[list["CaseTimelineEvent"]] = relationship(
        "CaseTimelineEvent",
        primaryjoin=(
            "app.modules.cases.domain.entities.compliance_case.ComplianceCase.id "
            "== CaseTimelineEvent.case_id"
        ),
        order_by="CaseTimelineEvent.occurred_at",
        viewonly=True,
    )
