"""Case Management Console — schema `cases` (Epic 4.3, ANER-4.3-S1T1)

Four tables, all created fresh in a new `cases` schema:

  cases.compliance_case       — one case: a screening hit, a reconciliation
                                 break, an onboarding review, or any of the
                                 other originating events this epic covers.
  cases.case_timeline_event   — the case's audit trail. Append-only.
  cases.case_evidence_item    — evidence attached to a case.
  cases.case_sla_config       — GitOps-seeded SLA policy per
                                 (case_type, severity) pair (ANER-4.3-S1T2).

NAMING COLLISION, NOTED SO IT IS NOT REDISCOVERED IN REVIEW.
`compliance.compliance_cases` already exists (compliance_0001, `app/modules/
compliance/domain/entities/compliance.py`) with its own `CaseType` and
`CaseStatus`. It is a narrower, older mechanism — `AppendOnlyModel`, so a row's
`status` can never change after insert; keyed only to `payments.transactions`,
so it cannot represent an onboarding review or a webhook delivery failure. It
is not reused, extended, or migrated into by this revision: Epic 4.3 needed a
case model neither its status-immutability nor its single foreign key could
support, and the ticket names the new table `compliance_case` (singular)
regardless. The two `CaseType` / `ComplianceCase` pairs are unrelated
vocabularies sharing a name across two schemas — see
`domain/entities/enums.py`'s module docstring for the full note. A future story
may want to decide whether `compliance.compliance_cases` should be
deprecated in favour of this table; that decision is out of scope here.

DESIGN DECISIONS WORTH STATING ONCE, NOT REDISCOVERED PER REVIEWER:

`case_reference` is generated by a trigger
(`cases.generate_case_reference()`), not by application code. The ticket asks
for "no gaps/duplicates under concurrent creation", which a native Postgres
`SEQUENCE` does not itself guarantee gap-free — a `SEQUENCE`'s counter advances
outside the transaction and is never rolled back, so an aborted insert still
burns a number. `cases.case_reference_sequence` is a plain counter table
instead, advanced with `INSERT ... ON CONFLICT (calendar_year) DO UPDATE`
inside the same transaction as the case row: the `UPDATE` takes a row lock
(serialising concurrent inserts, which is what actually prevents duplicates —
the same property a `SEQUENCE` has), and because it is *inside* the case's own
transaction, a rolled-back insert rolls the counter back with it, leaving no
gap. The trigger only fills `case_reference` when the caller leaves it NULL,
so a caller — or a test proving `uq_compliance_case_reference` — may still
supply an explicit value.

`case_sla_config.case_type` / `.severity` are plain `String`, not the
`case_type_enum` / `case_severity_enum` Postgres types `compliance_case` uses.
This is what the ANER-4.3-S1T2 ticket's field list specifies, and CHECK
constraints reproduce the same closed vocabulary at the database level without
introducing a second Postgres type for one config table
(`case_sla_config.py`'s module docstring has the full reasoning).

Column-level immutability (`compliance_case.id/case_reference/created_at/
resolved_at/resolved_by`, `case_evidence_item.added_at`) reuses the exact
`prevent_field_mutation_when_set()` pattern `customers_0002_review_lifecycle`
introduced: a column is guarded only once it holds a value, so a nullable
column guarded this way (`resolved_at`, `resolved_by`) may be set once and
never again, while a column that always holds a value from insert
(`created_at`, `added_at`) is immutable immediately. Each schema owns its own
copy of the function rather than sharing one across schemas, following that
same migration's precedent.

`case_timeline_event` is whole-table append-only via `public.prevent_mutation()`
(the shared function every append-only table in this repository uses),
`FOR EACH STATEMENT` — matching `customers_0002`/`customers_0003`'s more recent
convention rather than onboarding's `FOR EACH ROW`.

`case_evidence_item` is NOT whole-table append-only: an analyst may later
toggle `is_key_evidence` while triaging, so only `added_at` is guarded, at the
column level, not the row.

ENCRYPTED AT REST. `case_evidence_item.evidence_data` (for the PII-bearing
evidence types — screening results, KYB results, onboarding evidence,
travel-rule data, Reactor investigations) and `compliance_case.
evidence_package` are documented as encrypted-at-rest in the ticket. No
field-level encryption layer or KMS provider exists anywhere in this platform
yet — `onboarding_request.tax_identification_number` and `kyb_vendor_result.
raw_vendor_response` carry the identical, already-accepted gap. Both columns
here are plain JSONB, flagged in the entity docstrings, not silently assumed
safe. This is a platform gap, not a decision taken in this migration.

Every index here is built with the plain, transactional `CREATE INDEX`. The
constraint requiring `CONCURRENTLY` applies to tables that may hold production
data; these four are created empty in this same migration and hold none.

Revision ID: cases_0001_case_management
Revises: 0a772fd562e8
Create Date: 2026-09-17
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "cases_0001_case_management"
down_revision: str | None = "0a772fd562e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SCHEMA = "cases"


# ── Enums ─────────────────────────────────────────────────────────────────────
# Stored labels are the uppercase Python member names: these models do not pass
# values_callable, so SQLAlchemy persists `.name`.

case_type_enum = postgresql.ENUM(
    "SCREENING_REVIEW", "TRANSACTION_FLAG", "RECONCILIATION_BREAK",
    "RECONCILIATION_TIMEOUT", "ONBOARDING_REVIEW", "TRAVEL_RULE_REVIEW",
    "ON_CHAIN_ESCALATION", "WEBHOOK_DELIVERY_FAILURE", "MANUAL",
    name="case_type_enum", schema=SCHEMA, create_type=False,
)
case_status_enum = postgresql.ENUM(
    "OPEN", "ASSIGNED", "UNDER_INVESTIGATION", "PENDING_EXTERNAL",
    "PENDING_APPROVAL", "RESOLVED", "ESCALATED", "CLOSED_WITHOUT_ACTION",
    name="case_status_enum", schema=SCHEMA, create_type=False,
)
case_severity_enum = postgresql.ENUM(
    "CRITICAL", "HIGH", "MEDIUM", "LOW",
    name="case_severity_enum", schema=SCHEMA, create_type=False,
)
resolution_action_enum = postgresql.ENUM(
    "APPROVE_TRANSACTION", "DECLINE_TRANSACTION", "APPROVE_ONBOARDING",
    "REJECT_ONBOARDING", "APPROVE_RECALL", "MANUAL_RESOLUTION",
    "NO_ACTION_REQUIRED",
    name="resolution_action_enum", schema=SCHEMA, create_type=False,
)
timeline_event_type_enum = postgresql.ENUM(
    "CASE_CREATED", "ASSIGNED", "STATUS_CHANGED", "NOTE_ADDED",
    "EVIDENCE_UPDATED", "ESCALATED", "APPROVAL_REQUESTED",
    "APPROVAL_RECEIVED", "APPROVAL_REJECTED", "RESOLVED", "CLOSED",
    name="timeline_event_type_enum", schema=SCHEMA, create_type=False,
)
# Named case_actor_type_enum, not actor_type_enum: audit.actor_type_enum
# already exists with different members (SYSTEM, COMPLIANCE_OFFICER,
# API_CLIENT) and this schema does not reference or widen it — see
# domain/entities/enums.py's module docstring.
case_actor_type_enum = postgresql.ENUM(
    "COMPLIANCE_OFFICER", "OPERATIONS_OFFICER", "SYSTEM", "EXTERNAL_APPROVER",
    name="case_actor_type_enum", schema=SCHEMA, create_type=False,
)
evidence_type_enum = postgresql.ENUM(
    "SCREENING_RESULT", "KYB_RESULT", "ONBOARDING_EVIDENCE",
    "DECISIONING_RESULT", "LIMITS_CHECK", "FX_RATE_DATA",
    "RECONCILIATION_DATA", "TRAVEL_RULE_DATA", "ON_CHAIN_ASSESSMENT",
    "REACTOR_INVESTIGATION", "SETTLEMENT_RECORD", "MANUAL_ATTACHMENT",
    name="evidence_type_enum", schema=SCHEMA, create_type=False,
)

_ENUMS = (
    case_type_enum,
    case_status_enum,
    case_severity_enum,
    resolution_action_enum,
    timeline_event_type_enum,
    case_actor_type_enum,
    evidence_type_enum,
)

MIN_RESOLUTION_NOTE_LENGTH = 1

_CASE_TYPE_VALUES = (
    "SCREENING_REVIEW", "TRANSACTION_FLAG", "RECONCILIATION_BREAK",
    "RECONCILIATION_TIMEOUT", "ONBOARDING_REVIEW", "TRAVEL_RULE_REVIEW",
    "ON_CHAIN_ESCALATION", "WEBHOOK_DELIVERY_FAILURE", "MANUAL",
)
_SEVERITY_VALUES = ("CRITICAL", "HIGH", "MEDIUM", "LOW")
_CASE_TYPE_IN_LIST = ", ".join(f"'{v}'" for v in _CASE_TYPE_VALUES)
_SEVERITY_IN_LIST = ", ".join(f"'{v}'" for v in _SEVERITY_VALUES)

# Reused verbatim from customers_0002_review_lifecycle, scoped to this schema.
# A column is guarded only once it holds a value, so a nullable column guarded
# this way (resolved_at, resolved_by) may be set once and never again, while a
# column that always holds a value from insert (created_at) is immutable
# immediately.
_IMMUTABILITY_FUNCTION = """
CREATE OR REPLACE FUNCTION {schema}.prevent_field_mutation_when_set()
RETURNS TRIGGER AS $func$
DECLARE
    col_name text;
    old_json jsonb := to_jsonb(OLD);
    new_json jsonb := to_jsonb(NEW);
BEGIN
    FOR i IN 0 .. array_upper(TG_ARGV, 1) LOOP
        col_name := TG_ARGV[i];
        IF jsonb_typeof(old_json->col_name) IS DISTINCT FROM 'null'
           AND old_json->col_name IS DISTINCT FROM new_json->col_name THEN
            RAISE EXCEPTION 'Column % is immutable once set.', col_name;
        END IF;
    END LOOP;
    RETURN NEW;
END;
$func$ LANGUAGE plpgsql;
"""

# The per-calendar-year counter compliance_case.case_reference draws on. See
# the module docstring for why this is a locked counter table rather than a
# native SEQUENCE.
_CASE_REFERENCE_SEQUENCE_FUNCTION = """
CREATE OR REPLACE FUNCTION {schema}.generate_case_reference()
RETURNS TRIGGER AS $func$
DECLARE
    yr int;
    seq bigint;
BEGIN
    IF NEW.case_reference IS NOT NULL THEN
        RETURN NEW;
    END IF;

    yr := date_part('year', now())::int;

    INSERT INTO {schema}.case_reference_sequence (calendar_year, next_value)
    VALUES (yr, 1)
    ON CONFLICT (calendar_year) DO UPDATE
        SET next_value = {schema}.case_reference_sequence.next_value + 1
    RETURNING next_value INTO seq;

    NEW.case_reference := 'CASE-' || yr::text || '-' || lpad(seq::text, 5, '0');
    RETURN NEW;
END;
$func$ LANGUAGE plpgsql;
"""


def upgrade() -> None:
    bind = op.get_bind()

    op.execute(f"CREATE SCHEMA IF NOT EXISTS {SCHEMA}")

    for pg_enum in _ENUMS:
        pg_enum.create(bind, checkfirst=False)

    op.execute(_IMMUTABILITY_FUNCTION.format(schema=SCHEMA))

    # ── case_reference_sequence ────────────────────────────────────────────
    # One row per calendar year, advanced atomically by generate_case_reference().
    op.create_table(
        "case_reference_sequence",
        sa.Column("calendar_year", sa.Integer(), nullable=False),
        sa.Column("next_value", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("calendar_year", name="pk_case_reference_sequence"),
        schema=SCHEMA,
    )

    op.execute(_CASE_REFERENCE_SEQUENCE_FUNCTION.format(schema=SCHEMA))

    # ── compliance_case ────────────────────────────────────────────────────
    op.create_table(
        "compliance_case",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("case_reference", sa.String(length=64), nullable=False),
        sa.Column("case_type", case_type_enum, nullable=False),
        sa.Column("case_status", case_status_enum, nullable=False),
        sa.Column("severity", case_severity_enum, nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("customer_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("settlement_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("onboarding_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("originating_epic", sa.String(length=100), nullable=False),
        sa.Column("originating_event_type", sa.String(length=150), nullable=False),
        sa.Column("originating_event_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("assigned_to", sa.String(length=255), nullable=True),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sla_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sla_breached", sa.Boolean(), nullable=False),
        sa.Column("resolution_action", resolution_action_enum, nullable=True),
        sa.Column("resolution_note", sa.String(), nullable=True),
        sa.Column("resolution_approval_request_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.String(length=255), nullable=True),
        sa.Column(
            "evidence_package",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_compliance_case"),
        sa.UniqueConstraint("case_reference", name="uq_compliance_case_reference"),
        sa.CheckConstraint(
            "case_reference ~ '^CASE-[0-9]{4}-[0-9]+$'",
            name="ck_compliance_case_reference_format",
        ),
        sa.CheckConstraint(
            "priority BETWEEN 1 AND 5",
            name="ck_compliance_case_priority_range",
        ),
        sa.CheckConstraint(
            "resolution_action IS NULL OR ("
            " resolution_note IS NOT NULL"
            f" AND char_length(btrim(resolution_note)) >= {MIN_RESOLUTION_NOTE_LENGTH}"
            ")",
            name="ck_compliance_case_resolution_note_required",
        ),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_compliance_case_status_sla",
        "compliance_case",
        ["case_status", "sla_deadline"],
        schema=SCHEMA,
    )
    op.create_index(
        "ix_compliance_case_customer_id", "compliance_case", ["customer_id"], schema=SCHEMA
    )
    op.create_index(
        "ix_compliance_case_settlement_id", "compliance_case", ["settlement_id"], schema=SCHEMA
    )
    op.create_index(
        "ix_compliance_case_onboarding_id", "compliance_case", ["onboarding_id"], schema=SCHEMA
    )
    op.create_index(
        "ix_compliance_case_assigned_to", "compliance_case", ["assigned_to"], schema=SCHEMA
    )
    # The idempotency guard against duplicate Kafka events creating duplicate
    # cases. A plain UniqueConstraint would also forbid a second NULL, which is
    # the common case for cases with no single originating event (e.g. MANUAL)
    # — so this is a partial unique index, following the precedent of
    # onboarding_request's uq_onboarding_request_active_customer.
    op.create_index(
        "uq_compliance_case_originating_event_id",
        "compliance_case",
        ["originating_event_id"],
        unique=True,
        schema=SCHEMA,
        postgresql_where=sa.text("originating_event_id IS NOT NULL"),
    )

    # ── case_timeline_event ────────────────────────────────────────────────
    op.create_table(
        "case_timeline_event",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("case_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("event_type", timeline_event_type_enum, nullable=False),
        sa.Column("from_status", sa.String(length=100), nullable=True),
        sa.Column("to_status", sa.String(length=100), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("actor_type", case_actor_type_enum, nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_case_timeline_event"),
        # RESTRICT, not CASCADE: the timeline is the audit record of a case and
        # must outlive any attempt to remove the case it describes — the same
        # reasoning onboarding's case_state_transition_case_id_fkey documents.
        sa.ForeignKeyConstraint(
            ["case_id"],
            [f"{SCHEMA}.compliance_case.id"],
            name="fk_case_timeline_event_case_id",
            ondelete="RESTRICT",
        ),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_case_timeline_event_case_id", "case_timeline_event", ["case_id"], schema=SCHEMA
    )
    op.create_index(
        "ix_case_timeline_event_case_occurred",
        "case_timeline_event",
        ["case_id", "occurred_at"],
        schema=SCHEMA,
    )

    # ── case_evidence_item ─────────────────────────────────────────────────
    op.create_table(
        "case_evidence_item",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("case_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("evidence_type", evidence_type_enum, nullable=False),
        sa.Column("source_epic", sa.String(length=100), nullable=False),
        sa.Column("source_reference_id", postgresql.UUID(as_uuid=True), nullable=False),
        # Encrypted at rest for PII-bearing evidence types. See the module and
        # entity docstrings — no field-level encryption layer exists yet.
        sa.Column("evidence_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("added_by", sa.String(length=255), nullable=False),
        sa.Column(
            "is_key_evidence", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="pk_case_evidence_item"),
        sa.ForeignKeyConstraint(
            ["case_id"],
            [f"{SCHEMA}.compliance_case.id"],
            name="fk_case_evidence_item_case_id",
            ondelete="RESTRICT",
        ),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_case_evidence_item_case_id", "case_evidence_item", ["case_id"], schema=SCHEMA
    )
    op.create_index(
        "ix_case_evidence_item_case_type",
        "case_evidence_item",
        ["case_id", "evidence_type"],
        schema=SCHEMA,
    )

    # ── case_sla_config ────────────────────────────────────────────────────
    # case_type/severity are plain strings with CHECK constraints reproducing
    # the closed vocabulary, not the case_type_enum/case_severity_enum types
    # compliance_case uses — see the module docstring.
    op.create_table(
        "case_sla_config",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("case_type", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("sla_hours", sa.Integer(), nullable=False),
        sa.Column("auto_escalate_at_pct", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_case_sla_config"),
        sa.UniqueConstraint("case_type", "severity", name="uq_case_sla_config_type_severity"),
        sa.CheckConstraint(f"case_type IN ({_CASE_TYPE_IN_LIST})", name="ck_case_sla_config_case_type"),
        sa.CheckConstraint(f"severity IN ({_SEVERITY_IN_LIST})", name="ck_case_sla_config_severity"),
        sa.CheckConstraint("sla_hours > 0", name="ck_case_sla_config_sla_hours_positive"),
        sa.CheckConstraint(
            "auto_escalate_at_pct > 0 AND auto_escalate_at_pct <= 100",
            name="ck_case_sla_config_auto_escalate_pct_range",
        ),
        schema=SCHEMA,
    )

    # ── Triggers ─────────────────────────────────────────────────────────────
    op.execute(f"""
        CREATE TRIGGER trg_compliance_case_generate_reference
        BEFORE INSERT ON {SCHEMA}.compliance_case
        FOR EACH ROW
        EXECUTE FUNCTION {SCHEMA}.generate_case_reference();
    """)

    op.execute(f"""
        CREATE TRIGGER trg_compliance_case_field_immutability
        BEFORE UPDATE ON {SCHEMA}.compliance_case
        FOR EACH ROW
        EXECUTE FUNCTION {SCHEMA}.prevent_field_mutation_when_set(
            'id', 'case_reference', 'created_at', 'resolved_at', 'resolved_by'
        );
    """)

    op.execute(f"""
        CREATE TRIGGER trg_case_evidence_item_field_immutability
        BEFORE UPDATE ON {SCHEMA}.case_evidence_item
        FOR EACH ROW
        EXECUTE FUNCTION {SCHEMA}.prevent_field_mutation_when_set('added_at');
    """)

    # Whole-table append-only, FOR EACH STATEMENT — matching
    # customers_0002/customers_0003's convention.
    op.execute(f"""
        CREATE TRIGGER trg_case_timeline_event_append_only
        BEFORE UPDATE OR DELETE ON {SCHEMA}.case_timeline_event
        FOR EACH STATEMENT
        EXECUTE FUNCTION public.prevent_mutation();
    """)


def downgrade() -> None:
    op.execute(
        f"DROP TRIGGER IF EXISTS trg_case_timeline_event_append_only "
        f"ON {SCHEMA}.case_timeline_event;"
    )
    op.execute(
        f"DROP TRIGGER IF EXISTS trg_case_evidence_item_field_immutability "
        f"ON {SCHEMA}.case_evidence_item;"
    )
    op.execute(
        f"DROP TRIGGER IF EXISTS trg_compliance_case_field_immutability "
        f"ON {SCHEMA}.compliance_case;"
    )
    op.execute(
        f"DROP TRIGGER IF EXISTS trg_compliance_case_generate_reference "
        f"ON {SCHEMA}.compliance_case;"
    )

    # Reverse dependency order: children before compliance_case.
    op.drop_table("case_sla_config", schema=SCHEMA)
    op.drop_table("case_evidence_item", schema=SCHEMA)
    op.drop_table("case_timeline_event", schema=SCHEMA)
    op.drop_table("compliance_case", schema=SCHEMA)

    op.execute(f"DROP FUNCTION IF EXISTS {SCHEMA}.generate_case_reference() CASCADE;")
    op.drop_table("case_reference_sequence", schema=SCHEMA)

    op.execute(f"DROP FUNCTION IF EXISTS {SCHEMA}.prevent_field_mutation_when_set() CASCADE;")

    bind = op.get_bind()
    for pg_enum in reversed(_ENUMS):
        pg_enum.drop(bind, checkfirst=False)

    op.execute(f"DROP SCHEMA IF EXISTS {SCHEMA} CASCADE")
