// Writes src/design/icon-paths.ts from Phosphor's glyph definitions: the `regular`
// weight of every glyph in src/design/icon-names.ts, and `fill` for those in FILLED.
// Phosphor ships six weights per glyph; the app draws one (frontend-plan §5.5,
// §12.3), so copying the shapes keeps ~250 kB of unused paths out of the bundle.
//
// Run with `pnpm icons` after editing icon-names.ts. Needs Node 22.6+ (it imports the
// .ts names file with type stripping).

import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { FILLED, ICON_NAMES } from '../src/design/icon-names.ts';

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const defs = join(dirname(require.resolve('@phosphor-icons/react/package.json')), 'dist', 'defs');

/** A React element tree to [tag, attributes] pairs, flattening fragments. */
function shapes(element) {
  if (element == null || typeof element !== 'object') return [];
  if (Array.isArray(element)) return element.flatMap(shapes);
  const { children, ...attrs } = element.props ?? {};
  if (typeof element.type !== 'string') return shapes(children);
  return [[element.type, attrs], ...shapes(children)];
}

const entries = [];
for (const [key, glyph] of Object.entries(ICON_NAMES)) {
  const { default: weights } = await import(pathToFileURL(join(defs, `${glyph}.es.js`)).href);
  const drawn = { regular: shapes(weights.get('regular')) };
  if (FILLED.includes(key)) drawn.fill = shapes(weights.get('fill'));
  entries.push(`  ${glyph}: ${JSON.stringify(drawn)},`);
}

const unique = [...new Set(entries)].sort();
writeFileSync(
  join(here, '..', 'src', 'design', 'icon-paths.ts'),
  `// Generated by scripts/build-icons.mjs from @phosphor-icons/react — do not edit.
// Phosphor icons © Phosphor Icons, MIT licence.

export type IconShape = [string, Record<string, string | number>];

export const ICON_PATHS: Record<string, { regular: IconShape[]; fill?: IconShape[] }> = {
${unique.join('\n')}
};
`,
);
console.log(`icon-paths.ts: ${unique.length} glyphs`);
