// Writes src/design/icon-paths.ts from Fluent UI System Icons: the 20 px `regular`
// style of every glyph in src/design/icon-names.ts, and `filled` for those in FILLED.
// The package ships ~20,000 files (every glyph at six sizes and three styles); the
// app draws one size, so copying the paths keeps the rest out of the bundle
// (frontend-plan §5.8, §12.2).
//
// Run with `pnpm icons` after editing icon-names.ts. Needs Node 22.6+ (it imports the
// .ts names file with type stripping).

import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { FILLED, ICON_NAMES } from '../src/design/icon-names.ts';

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const icons = join(dirname(require.resolve('@fluentui/svg-icons/package.json')), 'icons');

/** An SVG file's drawn elements as [tag, attributes] pairs. */
function shapes(file) {
  const svg = readFileSync(join(icons, file), 'utf8');
  return [...svg.matchAll(/<(path|circle|rect)\s([^>]*?)\/?>/g)].map(([, tag, raw]) => [
    tag,
    Object.fromEntries(
      [...raw.matchAll(/([\w-]+)="([^"]*)"/g)].map(([, name, value]) => [
        // React spells SVG attributes in camelCase.
        name.replace(/-(\w)/g, (_, letter) => letter.toUpperCase()),
        value,
      ]),
    ),
  ]);
}

const entries = [];
for (const [key, glyph] of Object.entries(ICON_NAMES)) {
  const drawn = { regular: shapes(`${glyph}_20_regular.svg`) };
  if (FILLED.includes(key)) drawn.fill = shapes(`${glyph}_20_filled.svg`);
  entries.push(`  ${glyph}: ${JSON.stringify(drawn)},`);
}

const unique = [...new Set(entries)].sort();
writeFileSync(
  join(here, '..', 'src', 'design', 'icon-paths.ts'),
  `// Generated by scripts/build-icons.mjs from @fluentui/svg-icons — do not edit.
// Fluent UI System Icons © Microsoft Corporation, MIT licence.

export type IconShape = [string, Record<string, string | number>];

export const ICON_PATHS: Record<string, { regular: IconShape[]; fill?: IconShape[] }> = {
${unique.join('\n')}
};
`,
);
console.log(`icon-paths.ts: ${unique.length} glyphs`);
