import type { DocumentSource } from '../types';

/** Where a document came from, said honestly — a staff upload of the exporter's paperwork is the exporter's. */
export const SOURCE_LABEL: Record<DocumentSource, string> = {
  EXPORTER_UPLOAD: 'From the exporter (uploaded by staff)',
  INTERNAL: 'Produced internally',
  RXIL: 'From RXIL',
  SYSTEM: 'Generated by the system',
};
