"""Persistent compliance-review checklist state for the Exporter CRM (E9)."""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, Index, String, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.platform.database.models import AnerModel

SCHEMA = "onboarding"


class ScreeningReviewItem(AnerModel):
    __tablename__ = "screening_review_item"
    __table_args__ = (
        UniqueConstraint("customer_id", "item_key", name="uq_screening_review_customer_item"),
        Index("ix_screening_review_customer_id", "customer_id"),
        {"schema": SCHEMA},
    )

    customer_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    item_key: Mapped[str] = mapped_column(String(100), nullable=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False, default="NEEDS_REVIEW")
    comment: Mapped[str | None] = mapped_column(Text, nullable=True)
    reviewed_by: Mapped[str | None] = mapped_column(String(255), nullable=True)
    reviewed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


class BankActivityFinding(AnerModel):
    """Provider-originated bank/activity signal. E9 only exposes read APIs.

    Real Surepass/Finpass ingestion can write these rows later without changing
    the CRM contract or UI. No fake findings are generated by E9.
    """

    __tablename__ = "bank_activity_finding"
    __table_args__ = (
        Index("ix_bank_activity_finding_customer_id", "customer_id"),
        Index("ix_bank_activity_finding_customer_status", "customer_id", "status"),
        {"schema": SCHEMA},
    )

    customer_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    provider: Mapped[str] = mapped_column(String(100), nullable=False)
    finding_type: Mapped[str] = mapped_column(String(100), nullable=False)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    risk_level: Mapped[str] = mapped_column(String(32), nullable=False, default="REVIEW")
    status: Mapped[str] = mapped_column(String(32), nullable=False, default="OPEN")
    provider_reference: Mapped[str | None] = mapped_column(String(255), nullable=True)
    detected_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


__all__ = ["ScreeningReviewItem", "BankActivityFinding"]
